//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptar.
        /// </summary>
        internal static string btnAceptar {
            get {
                return ResourceManager.GetString("btnAceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizar.
        /// </summary>
        internal static string btnActualizar {
            get {
                return ResourceManager.GetString("btnActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoteles Administrar.
        /// </summary>
        internal static string btnAdministrarHotel {
            get {
                return ResourceManager.GetString("btnAdministrarHotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar Suite.
        /// </summary>
        internal static string btnAgregarSuit {
            get {
                return ResourceManager.GetString("btnAgregarSuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar.
        /// </summary>
        internal static string btnBuscar {
            get {
                return ResourceManager.GetString("btnBuscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string btnCancelar {
            get {
                return ResourceManager.GetString("btnCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargar Archivo.
        /// </summary>
        internal static string btnCargarArchivo {
            get {
                return ResourceManager.GetString("btnCargarArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descargar.
        /// </summary>
        internal static string btnDescargar {
            get {
                return ResourceManager.GetString("btnDescargar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        internal static string btnEditar {
            get {
                return ResourceManager.GetString("btnEditar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar Extractos.
        /// </summary>
        internal static string btnEnviarExtractos {
            get {
                return ResourceManager.GetString("btnEnviarExtractos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportar Propietarios.
        /// </summary>
        internal static string btnExportarCopropietario {
            get {
                return ResourceManager.GetString("btnExportarCopropietario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportar Regla.
        /// </summary>
        internal static string btnExportarRegla {
            get {
                return ResourceManager.GetString("btnExportarRegla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportar Variable.
        /// </summary>
        internal static string btnExportarVariables {
            get {
                return ResourceManager.GetString("btnExportarVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        internal static string btnGuardar {
            get {
                return ResourceManager.GetString("btnGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar.
        /// </summary>
        internal static string btnModificar {
            get {
                return ResourceManager.GetString("btnModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo.
        /// </summary>
        internal static string btnNuevo {
            get {
                return ResourceManager.GetString("btnNuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probar Regla.
        /// </summary>
        internal static string btnProbarRegla {
            get {
                return ResourceManager.GetString("btnProbarRegla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar.
        /// </summary>
        internal static string btnSeleccionar {
            get {
                return ResourceManager.GetString("btnSeleccionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Extracto.
        /// </summary>
        internal static string btnVerExtracto {
            get {
                return ResourceManager.GetString("btnVerExtracto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View History.
        /// </summary>
        internal static string btnVerHistorial {
            get {
                return ResourceManager.GetString("btnVerHistorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Todos.
        /// </summary>
        internal static string btnVerTodos {
            get {
                return ResourceManager.GetString("btnVerTodos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar Sesion.
        /// </summary>
        internal static string CerrarSesion {
            get {
                return ResourceManager.GetString("CerrarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos Centro Costo.
        /// </summary>
        internal static string DatosCeCo {
            get {
                return ResourceManager.GetString("DatosCeCo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos Concepto.
        /// </summary>
        internal static string DatosConcepto {
            get {
                return ResourceManager.GetString("DatosConcepto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos Cuenta Contable.
        /// </summary>
        internal static string DatosCuentaContable {
            get {
                return ResourceManager.GetString("DatosCuentaContable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos Hoteles.
        /// </summary>
        internal static string DatosHotel {
            get {
                return ResourceManager.GetString("DatosHotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos Noticia.
        /// </summary>
        internal static string DatosNoticia {
            get {
                return ResourceManager.GetString("DatosNoticia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos Perfil - Permisos.
        /// </summary>
        internal static string DatosPerfilpermiso {
            get {
                return ResourceManager.GetString("DatosPerfilpermiso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos Propietarios.
        /// </summary>
        internal static string DatosPropietario {
            get {
                return ResourceManager.GetString("DatosPropietario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos Propietarios.
        /// </summary>
        internal static string DatosPropietarioCliente {
            get {
                return ResourceManager.GetString("DatosPropietarioCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos Usuario.
        /// </summary>
        internal static string DatosPropietarioUsuario {
            get {
                return ResourceManager.GetString("DatosPropietarioUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos Recerva.
        /// </summary>
        internal static string DatosReserva {
            get {
                return ResourceManager.GetString("DatosReserva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos Suite.
        /// </summary>
        internal static string DatosSuit {
            get {
                return ResourceManager.GetString("DatosSuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos Variables.
        /// </summary>
        internal static string DatosVariables {
            get {
                return ResourceManager.GetString("DatosVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrir Liquidacion.
        /// </summary>
        internal static string lblAbrirLiquidacion {
            get {
                return ResourceManager.GetString("lblAbrirLiquidacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acción.
        /// </summary>
        internal static string lblAccion {
            get {
                return ResourceManager.GetString("lblAccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activo.
        /// </summary>
        internal static string lblActivo {
            get {
                return ResourceManager.GetString("lblActivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administra.
        /// </summary>
        internal static string lblAdmin {
            get {
                return ResourceManager.GetString("lblAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adultos.
        /// </summary>
        internal static string lblAdulto {
            get {
                return ResourceManager.GetString("lblAdulto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar Suite.
        /// </summary>
        internal static string lblAgregarSuite {
            get {
                return ResourceManager.GetString("lblAgregarSuite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Año.
        /// </summary>
        internal static string lblAno {
            get {
                return ResourceManager.GetString("lblAno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido.
        /// </summary>
        internal static string lblApellido {
            get {
                return ResourceManager.GetString("lblApellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segundo Apellido.
        /// </summary>
        internal static string lblApellidoDos {
            get {
                return ResourceManager.GetString("lblApellidoDos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido.
        /// </summary>
        internal static string lblApellidoSolo {
            get {
                return ResourceManager.GetString("lblApellidoSolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivo.
        /// </summary>
        internal static string lblArchivo {
            get {
                return ResourceManager.GetString("lblArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        internal static string lblArea {
            get {
                return ResourceManager.GetString("lblArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asunto Correo.
        /// </summary>
        internal static string lblAsuntoCorreo {
            get {
                return ResourceManager.GetString("lblAsuntoCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auditoria.
        /// </summary>
        internal static string lblAuditoria {
            get {
                return ResourceManager.GetString("lblAuditoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los valores de porcentajes, debe ir expresdas en decimales..
        /// </summary>
        internal static string lblAyudaPorcentaje {
            get {
                return ResourceManager.GetString("lblAyudaPorcentaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banco.
        /// </summary>
        internal static string lblBanco {
            get {
                return ResourceManager.GetString("lblBanco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar por.
        /// </summary>
        internal static string lblBuscarPor {
            get {
                return ResourceManager.GetString("lblBuscarPor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar Propietarios.
        /// </summary>
        internal static string lblbuscarProp {
            get {
                return ResourceManager.GetString("lblbuscarProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar Clave.
        /// </summary>
        internal static string lblCambioClave {
            get {
                return ResourceManager.GetString("lblCambioClave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargando....
        /// </summary>
        internal static string lblCargando {
            get {
                return ResourceManager.GetString("lblCargando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centro Costo.
        /// </summary>
        internal static string lblCentroCosto {
            get {
                return ResourceManager.GetString("lblCentroCosto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centro Costo Variable.
        /// </summary>
        internal static string lblCentroCostoVariable {
            get {
                return ResourceManager.GetString("lblCentroCostoVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificado.
        /// </summary>
        internal static string lblCertificado {
            get {
                return ResourceManager.GetString("lblCertificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cierre Liquidación.
        /// </summary>
        internal static string lblCierreLiquidacion {
            get {
                return ResourceManager.GetString("lblCierreLiquidacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciudad.
        /// </summary>
        internal static string lblCiudad {
            get {
                return ResourceManager.GetString("lblCiudad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clave.
        /// </summary>
        internal static string lblClave {
            get {
                return ResourceManager.GetString("lblClave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clave Actual.
        /// </summary>
        internal static string lblClaveActual {
            get {
                return ResourceManager.GetString("lblClaveActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar Clave.
        /// </summary>
        internal static string lblClaveConfirmar {
            get {
                return ResourceManager.GetString("lblClaveConfirmar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clave Nueva.
        /// </summary>
        internal static string lblClaveNueva {
            get {
                return ResourceManager.GetString("lblClaveNueva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codigo.
        /// </summary>
        internal static string lblCodigo {
            get {
                return ResourceManager.GetString("lblCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codigo Tercero.
        /// </summary>
        internal static string lblCodigoTercero {
            get {
                return ResourceManager.GetString("lblCodigoTercero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concepto.
        /// </summary>
        internal static string lblConcepto {
            get {
                return ResourceManager.GetString("lblConcepto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuracion Certificado.
        /// </summary>
        internal static string lblConfigCertificado {
            get {
                return ResourceManager.GetString("lblConfigCertificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuración Extracto.
        /// </summary>
        internal static string lblConfigExtracto {
            get {
                return ResourceManager.GetString("lblConfigExtracto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuración Reportes.
        /// </summary>
        internal static string lblConfigReporte {
            get {
                return ResourceManager.GetString("lblConfigReporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo.
        /// </summary>
        internal static string lblCorreo {
            get {
                return ResourceManager.GetString("lblCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo Contacto.
        /// </summary>
        internal static string lblCorreoContacto {
            get {
                return ResourceManager.GetString("lblCorreoContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N° Cuenta.
        /// </summary>
        internal static string lblCuenta {
            get {
                return ResourceManager.GetString("lblCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuenta de Ahorro.
        /// </summary>
        internal static string lblCuentaAhorro {
            get {
                return ResourceManager.GetString("lblCuentaAhorro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuenta Contable.
        /// </summary>
        internal static string lblCuentaContable {
            get {
                return ResourceManager.GetString("lblCuentaContable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuenta Corriente.
        /// </summary>
        internal static string lblCuentaCorriente {
            get {
                return ResourceManager.GetString("lblCuentaCorriente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departamento.
        /// </summary>
        internal static string lblDepto {
            get {
                return ResourceManager.GetString("lblDepto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descargar Archivo.
        /// </summary>
        internal static string lblDescargarArchivo {
            get {
                return ResourceManager.GetString("lblDescargarArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        internal static string lblDescripcion {
            get {
                return ResourceManager.GetString("lblDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle.
        /// </summary>
        internal static string lblDetalle {
            get {
                return ResourceManager.GetString("lblDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle Concepto Hotel.
        /// </summary>
        internal static string lblDetalleConceptoHotel {
            get {
                return ResourceManager.GetString("lblDetalleConceptoHotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección.
        /// </summary>
        internal static string lblDireccion {
            get {
                return ResourceManager.GetString("lblDireccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento Cruce.
        /// </summary>
        internal static string lblDocCruce {
            get {
                return ResourceManager.GetString("lblDocCruce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        internal static string lblEliminar {
            get {
                return ResourceManager.GetString("lblEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encabezado Documento Cruce.
        /// </summary>
        internal static string lblEncabezadoDocCruce {
            get {
                return ResourceManager.GetString("lblEncabezadoDocCruce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrada.
        /// </summary>
        internal static string lblEntrada {
            get {
                return ResourceManager.GetString("lblEntrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escritura.
        /// </summary>
        internal static string lblEscritura {
            get {
                return ResourceManager.GetString("lblEscritura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estadias.
        /// </summary>
        internal static string lblEstadia {
            get {
                return ResourceManager.GetString("lblEstadia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de Estadias.
        /// </summary>
        internal static string lblEstadias {
            get {
                return ResourceManager.GetString("lblEstadias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        internal static string lblEstado {
            get {
                return ResourceManager.GetString("lblEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracto.
        /// </summary>
        internal static string lblEstracto {
            get {
                return ResourceManager.GetString("lblEstracto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estructura.
        /// </summary>
        internal static string lblEstructura {
            get {
                return ResourceManager.GetString("lblEstructura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        internal static string lblFecha {
            get {
                return ResourceManager.GetString("lblFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Caducidad.
        /// </summary>
        internal static string lblFechaCaducidad {
            get {
                return ResourceManager.GetString("lblFechaCaducidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Creación.
        /// </summary>
        internal static string lblFechaCreacion {
            get {
                return ResourceManager.GetString("lblFechaCreacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Creación.
        /// </summary>
        internal static string lblFechaElaboracion {
            get {
                return ResourceManager.GetString("lblFechaElaboracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha filtro.
        /// </summary>
        internal static string lblFechaFiltro {
            get {
                return ResourceManager.GetString("lblFechaFiltro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha salida.
        /// </summary>
        internal static string lblFechaFin {
            get {
                return ResourceManager.GetString("lblFechaFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha llegada.
        /// </summary>
        internal static string lblFechaInicio {
            get {
                return ResourceManager.GetString("lblFechaInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Reserva.
        /// </summary>
        internal static string lblFechaReserva {
            get {
                return ResourceManager.GetString("lblFechaReserva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtro.
        /// </summary>
        internal static string lblFiltro {
            get {
                return ResourceManager.GetString("lblFiltro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historial.
        /// </summary>
        internal static string lblHistorial {
            get {
                return ResourceManager.GetString("lblHistorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historial Liquidación.
        /// </summary>
        internal static string lblHistorialLiquidacion {
            get {
                return ResourceManager.GetString("lblHistorialLiquidacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel.
        /// </summary>
        internal static string lblHotel {
            get {
                return ResourceManager.GetString("lblHotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel - Suite.
        /// </summary>
        internal static string lblHotelSuite {
            get {
                return ResourceManager.GetString("lblHotelSuite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información Estadistica.
        /// </summary>
        internal static string lblInfomacionEstadistica {
            get {
                return ResourceManager.GetString("lblInfomacionEstadistica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interfaz BOF.
        /// </summary>
        internal static string lblInterfaz {
            get {
                return ResourceManager.GetString("lblInterfaz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liquidación.
        /// </summary>
        internal static string lblLiquidacion {
            get {
                return ResourceManager.GetString("lblLiquidacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liquidación Hotel.
        /// </summary>
        internal static string lblLiquidacionHotel {
            get {
                return ResourceManager.GetString("lblLiquidacionHotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liquidación Propietario.
        /// </summary>
        internal static string lblLiquidacionPropietario {
            get {
                return ResourceManager.GetString("lblLiquidacionPropietario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liquidar.
        /// </summary>
        internal static string lblLiquidar {
            get {
                return ResourceManager.GetString("lblLiquidar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liquidar Seleccionados.
        /// </summary>
        internal static string lblLiquidarSeleccionados {
            get {
                return ResourceManager.GetString("lblLiquidarSeleccionados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liquidar Todos.
        /// </summary>
        internal static string lblLiquidarTodos {
            get {
                return ResourceManager.GetString("lblLiquidarTodos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Llave.
        /// </summary>
        internal static string lblLlave {
            get {
                return ResourceManager.GetString("lblLlave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string lblLogin {
            get {
                return ResourceManager.GetString("lblLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        internal static string lblLogo {
            get {
                return ResourceManager.GetString("lblLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Esta seguro de abrir esta liquidación?.
        /// </summary>
        internal static string lblMensajeAbrirLiquidacion {
            get {
                return ResourceManager.GetString("lblMensajeAbrirLiquidacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La actualización fue exitosa..
        /// </summary>
        internal static string lblMensajeActualizar {
            get {
                return ResourceManager.GetString("lblMensajeActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los campos de naranja, es información que no se encuentra guardada en la base de datos..
        /// </summary>
        internal static string lblMensajeAdvertencia_1 {
            get {
                return ResourceManager.GetString("lblMensajeAdvertencia_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivo generado con exito..
        /// </summary>
        internal static string lblMensajeArchivoGenerado {
            get {
                return ResourceManager.GetString("lblMensajeArchivoGenerado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carga Exitosa..
        /// </summary>
        internal static string lblMensajeCargue {
            get {
                return ResourceManager.GetString("lblMensajeCargue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todas cuentas contables, ya han sido asignadas..
        /// </summary>
        internal static string lblMensajeCuentasContables {
            get {
                return ResourceManager.GetString("lblMensajeCuentasContables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro Eliminado..
        /// </summary>
        internal static string lblMensajeEliminar {
            get {
                return ResourceManager.GetString("lblMensajeEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Esta seguro de eliminar este registro?.
        /// </summary>
        internal static string lblMensajeEliminarPregunta {
            get {
                return ResourceManager.GetString("lblMensajeEliminarPregunta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este registro depende de otra tabla..
        /// </summary>
        internal static string lblMensajeError_1 {
            get {
                return ResourceManager.GetString("lblMensajeError_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificación ya existe..
        /// </summary>
        internal static string lblMensajeError_10 {
            get {
                return ResourceManager.GetString("lblMensajeError_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clave actual invalida.
        /// </summary>
        internal static string lblMensajeError_11 {
            get {
                return ResourceManager.GetString("lblMensajeError_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El número suite ya existe..
        /// </summary>
        internal static string lblMensajeError_12 {
            get {
                return ResourceManager.GetString("lblMensajeError_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nit ya existe..
        /// </summary>
        internal static string lblMensajeError_13 {
            get {
                return ResourceManager.GetString("lblMensajeError_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las siguientes variables, aún no tienen valores asignados..
        /// </summary>
        internal static string lblMensajeError_14 {
            get {
                return ResourceManager.GetString("lblMensajeError_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El propietario debe tener asociado por lo menos una suite..
        /// </summary>
        internal static string lblMensajeError_15 {
            get {
                return ResourceManager.GetString("lblMensajeError_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El código ya existe..
        /// </summary>
        internal static string lblMensajeError_16 {
            get {
                return ResourceManager.GetString("lblMensajeError_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha de salida, debe ser mayor que la de llegada..
        /// </summary>
        internal static string lblMensajeError_17 {
            get {
                return ResourceManager.GetString("lblMensajeError_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has excedido el número de estadias permitido..
        /// </summary>
        internal static string lblMensajeError_18 {
            get {
                return ResourceManager.GetString("lblMensajeError_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta liquidación ya ha sido cerrada..
        /// </summary>
        internal static string lblMensajeError_19 {
            get {
                return ResourceManager.GetString("lblMensajeError_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clave y Confirmar clave deben ser iguales..
        /// </summary>
        internal static string lblMensajeError_2 {
            get {
                return ResourceManager.GetString("lblMensajeError_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los conceptos de hotel, deben ser liquidados primero..
        /// </summary>
        internal static string lblMensajeError_20 {
            get {
                return ResourceManager.GetString("lblMensajeError_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login ya existe..
        /// </summary>
        internal static string lblMensajeError_21 {
            get {
                return ResourceManager.GetString("lblMensajeError_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta liquidación no se puede eliminar, por que esta en estado cerrada..
        /// </summary>
        internal static string lblMensajeError_22 {
            get {
                return ResourceManager.GetString("lblMensajeError_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede eliminar esta relación, porque hace parte de una liquidación..
        /// </summary>
        internal static string lblMensajeError_23 {
            get {
                return ResourceManager.GetString("lblMensajeError_23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La regla, tiene errores de jerarquia.
        /// </summary>
        internal static string lblMensajeError_3 {
            get {
                return ResourceManager.GetString("lblMensajeError_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta variable ya existe..
        /// </summary>
        internal static string lblMensajeError_4 {
            get {
                return ResourceManager.GetString("lblMensajeError_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este usuario no esta activo ó algunos de los campos es incorrecto..
        /// </summary>
        internal static string lblMensajeError_5 {
            get {
                return ResourceManager.GetString("lblMensajeError_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hubo un problema, comuniquese con el administrador..
        /// </summary>
        internal static string lblMensajeError_6 {
            get {
                return ResourceManager.GetString("lblMensajeError_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login ya existe..
        /// </summary>
        internal static string lblMensajeError_7 {
            get {
                return ResourceManager.GetString("lblMensajeError_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La cadena no tiene el formato correcto..
        /// </summary>
        internal static string lblMensajeError_8 {
            get {
                return ResourceManager.GetString("lblMensajeError_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este registro no se puede eliminar, depende de otro registro..
        /// </summary>
        internal static string lblMensajeError_9 {
            get {
                return ResourceManager.GetString("lblMensajeError_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La regla, esta bien creada..
        /// </summary>
        internal static string lblMensajeExito_1 {
            get {
                return ResourceManager.GetString("lblMensajeExito_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro guardado con exito..
        /// </summary>
        internal static string lblMensajeGuardar {
            get {
                return ResourceManager.GetString("lblMensajeGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrar concepto en extracto.
        /// </summary>
        internal static string lblMostrarEnExtracto {
            get {
                return ResourceManager.GetString("lblMostrarEnExtracto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naturaleza Cuenta.
        /// </summary>
        internal static string lblNaturalezaCuenta {
            get {
                return ResourceManager.GetString("lblNaturalezaCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niños.
        /// </summary>
        internal static string lblNinos {
            get {
                return ResourceManager.GetString("lblNinos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nit.
        /// </summary>
        internal static string lblNit {
            get {
                return ResourceManager.GetString("lblNit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primer Nombre.
        /// </summary>
        internal static string lblNombre {
            get {
                return ResourceManager.GetString("lblNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre Concepto.
        /// </summary>
        internal static string lblNombreConcepto {
            get {
                return ResourceManager.GetString("lblNombreConcepto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre Contacto.
        /// </summary>
        internal static string lblNombreContacto {
            get {
                return ResourceManager.GetString("lblNombreContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segundo Nombre.
        /// </summary>
        internal static string lblNombreDos {
            get {
                return ResourceManager.GetString("lblNombreDos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre extracto.
        /// </summary>
        internal static string lblNombreExtracto {
            get {
                return ResourceManager.GetString("lblNombreExtracto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre Perfil.
        /// </summary>
        internal static string lblNombrePerfil {
            get {
                return ResourceManager.GetString("lblNombrePerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        internal static string lblNombreSolo {
            get {
                return ResourceManager.GetString("lblNombreSolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noticia.
        /// </summary>
        internal static string lblNoticia {
            get {
                return ResourceManager.GetString("lblNoticia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N° Cuenta.
        /// </summary>
        internal static string lblNumCuenta {
            get {
                return ResourceManager.GetString("lblNumCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero de Decimales.
        /// </summary>
        internal static string lblNumDecimales {
            get {
                return ResourceManager.GetString("lblNumDecimales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N° Dias.
        /// </summary>
        internal static string lblNumDias {
            get {
                return ResourceManager.GetString("lblNumDias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N° Identificación.
        /// </summary>
        internal static string lblNumIdentificacion {
            get {
                return ResourceManager.GetString("lblNumIdentificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N° Suite.
        /// </summary>
        internal static string lblNumSuit {
            get {
                return ResourceManager.GetString("lblNumSuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observación.
        /// </summary>
        internal static string lblObservacion {
            get {
                return ResourceManager.GetString("lblObservacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operadores.
        /// </summary>
        internal static string lblOperadores {
            get {
                return ResourceManager.GetString("lblOperadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil.
        /// </summary>
        internal static string lblPerfil {
            get {
                return ResourceManager.GetString("lblPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil - Permisos.
        /// </summary>
        internal static string lblPerfilPermisos {
            get {
                return ResourceManager.GetString("lblPerfilPermisos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periodo.
        /// </summary>
        internal static string lblPeriodo {
            get {
                return ResourceManager.GetString("lblPeriodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porcentaje Participación.
        /// </summary>
        internal static string lblPorcentajeParticipacion {
            get {
                return ResourceManager.GetString("lblPorcentajeParticipacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista Propietarios.
        /// </summary>
        internal static string lblPropietarios {
            get {
                return ResourceManager.GetString("lblPropietarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro Estadías.
        /// </summary>
        internal static string lblRegistroEstadias {
            get {
                return ResourceManager.GetString("lblRegistroEstadias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro Notaria.
        /// </summary>
        internal static string lblRegistroNotaria {
            get {
                return ResourceManager.GetString("lblRegistroNotaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regla.
        /// </summary>
        internal static string lblRegla {
            get {
                return ResourceManager.GetString("lblRegla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regla de Liquidación.
        /// </summary>
        internal static string lblReglaValidacion {
            get {
                return ResourceManager.GetString("lblReglaValidacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporte.
        /// </summary>
        internal static string lblReporte {
            get {
                return ResourceManager.GetString("lblReporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsable.
        /// </summary>
        internal static string lblResponsable {
            get {
                return ResourceManager.GetString("lblResponsable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salida.
        /// </summary>
        internal static string lblSalida {
            get {
                return ResourceManager.GetString("lblSalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selección.
        /// </summary>
        internal static string lblSeleccion {
            get {
                return ResourceManager.GetString("lblSeleccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione....
        /// </summary>
        internal static string lblSeleccione {
            get {
                return ResourceManager.GetString("lblSeleccione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separador.
        /// </summary>
        internal static string lblSeparador {
            get {
                return ResourceManager.GetString("lblSeparador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar Sesión.
        /// </summary>
        internal static string lblSesion {
            get {
                return ResourceManager.GetString("lblSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suite.
        /// </summary>
        internal static string lblSuit {
            get {
                return ResourceManager.GetString("lblSuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefono 1.
        /// </summary>
        internal static string lblTelefono1 {
            get {
                return ResourceManager.GetString("lblTelefono1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefono 2.
        /// </summary>
        internal static string lblTelefono2 {
            get {
                return ResourceManager.GetString("lblTelefono2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefono 3.
        /// </summary>
        internal static string lblTelefono3 {
            get {
                return ResourceManager.GetString("lblTelefono3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefono Contacto.
        /// </summary>
        internal static string lblTelefonoContacto {
            get {
                return ResourceManager.GetString("lblTelefonoContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tercero Variable.
        /// </summary>
        internal static string lblTerceroVariable {
            get {
                return ResourceManager.GetString("lblTerceroVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiene Permiso.
        /// </summary>
        internal static string lblTienePermiso {
            get {
                return ResourceManager.GetString("lblTienePermiso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Concepto.
        /// </summary>
        internal static string lblTipoConcepto {
            get {
                return ResourceManager.GetString("lblTipoConcepto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo cuenta.
        /// </summary>
        internal static string lblTipoCuenta {
            get {
                return ResourceManager.GetString("lblTipoCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Documento.
        /// </summary>
        internal static string lblTipoDocumento {
            get {
                return ResourceManager.GetString("lblTipoDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Persona.
        /// </summary>
        internal static string lblTipoPersona {
            get {
                return ResourceManager.GetString("lblTipoPersona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Variable.
        /// </summary>
        internal static string lblTipoVariable {
            get {
                return ResourceManager.GetString("lblTipoVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titular Cuenta.
        /// </summary>
        internal static string lblTitular {
            get {
                return ResourceManager.GetString("lblTitular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titulo.
        /// </summary>
        internal static string lblTitulo {
            get {
                return ResourceManager.GetString("lblTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos.
        /// </summary>
        internal static string lblTodos {
            get {
                return ResourceManager.GetString("lblTodos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidad de Negocio.
        /// </summary>
        internal static string lblUnidadNegocio {
            get {
                return ResourceManager.GetString("lblUnidadNegocio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        internal static string lblUsuario {
            get {
                return ResourceManager.GetString("lblUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuarios.
        /// </summary>
        internal static string lblusuarios {
            get {
                return ResourceManager.GetString("lblusuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor.
        /// </summary>
        internal static string lblValor {
            get {
                return ResourceManager.GetString("lblValor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor Variable Hotel.
        /// </summary>
        internal static string lblValorVariable {
            get {
                return ResourceManager.GetString("lblValorVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variables.
        /// </summary>
        internal static string lblVariables {
            get {
                return ResourceManager.GetString("lblVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable Generales.
        /// </summary>
        internal static string lblVariablesGenerales {
            get {
                return ResourceManager.GetString("lblVariablesGenerales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable Hotel.
        /// </summary>
        internal static string lblVariablesHotel {
            get {
                return ResourceManager.GetString("lblVariablesHotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable Propietario.
        /// </summary>
        internal static string lblVariablesPropietarios {
            get {
                return ResourceManager.GetString("lblVariablesPropietarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modulos.
        /// </summary>
        internal static string Modulos {
            get {
                return ResourceManager.GetString("Modulos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista Centro Costo.
        /// </summary>
        internal static string TituloCeCo {
            get {
                return ResourceManager.GetString("TituloCeCo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista Conceptos.
        /// </summary>
        internal static string TituloGrillaConcepto {
            get {
                return ResourceManager.GetString("TituloGrillaConcepto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista Cuenta Contable.
        /// </summary>
        internal static string TituloGrillaCuentaContable {
            get {
                return ResourceManager.GetString("TituloGrillaCuentaContable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista Hoteles.
        /// </summary>
        internal static string TituloGrillaHotel {
            get {
                return ResourceManager.GetString("TituloGrillaHotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista Liquidación.
        /// </summary>
        internal static string TituloGrillaLiquidacion {
            get {
                return ResourceManager.GetString("TituloGrillaLiquidacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista Modulos.
        /// </summary>
        internal static string TituloGrillaModulos {
            get {
                return ResourceManager.GetString("TituloGrillaModulos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista Noticias.
        /// </summary>
        internal static string TituloGrillaNoticia {
            get {
                return ResourceManager.GetString("TituloGrillaNoticia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista Perfil.
        /// </summary>
        internal static string TituloGrillaPerfil {
            get {
                return ResourceManager.GetString("TituloGrillaPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propietarios.
        /// </summary>
        internal static string TituloGrillaPropietarios {
            get {
                return ResourceManager.GetString("TituloGrillaPropietarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista Regla.
        /// </summary>
        internal static string TituloGrillaReglas {
            get {
                return ResourceManager.GetString("TituloGrillaReglas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista Reservas.
        /// </summary>
        internal static string TituloGrillaReservas {
            get {
                return ResourceManager.GetString("TituloGrillaReservas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraros datos..
        /// </summary>
        internal static string TituloGrillaSinDatos {
            get {
                return ResourceManager.GetString("TituloGrillaSinDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista Suite.
        /// </summary>
        internal static string TituloGrillaSuit {
            get {
                return ResourceManager.GetString("TituloGrillaSuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista Usuarios.
        /// </summary>
        internal static string TituloGrillaUsuario {
            get {
                return ResourceManager.GetString("TituloGrillaUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carga de Archivos.
        /// </summary>
        internal static string TituloPrincipalCargaMasiva {
            get {
                return ResourceManager.GetString("TituloPrincipalCargaMasiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoteles.
        /// </summary>
        internal static string TituloPrincipalHotel {
            get {
                return ResourceManager.GetString("TituloPrincipalHotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noticia.
        /// </summary>
        internal static string TituloPrincipalNoticia {
            get {
                return ResourceManager.GetString("TituloPrincipalNoticia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil - Permisos.
        /// </summary>
        internal static string TituloPrincipalPerfilPermiso {
            get {
                return ResourceManager.GetString("TituloPrincipalPerfilPermiso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propietarios.
        /// </summary>
        internal static string TituloprincipalPropietario {
            get {
                return ResourceManager.GetString("TituloprincipalPropietario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propietario.
        /// </summary>
        internal static string TituloprincipalPropietarioCliente {
            get {
                return ResourceManager.GetString("TituloprincipalPropietarioCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reglas de Liquidación.
        /// </summary>
        internal static string TituloprincipalReglaLiquidacion {
            get {
                return ResourceManager.GetString("TituloprincipalReglaLiquidacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuenta Contable - Hotel.
        /// </summary>
        internal static string TituloPrincipalRelacionContableHotel {
            get {
                return ResourceManager.GetString("TituloPrincipalRelacionContableHotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservación.
        /// </summary>
        internal static string TituloPrincipalReservaciones {
            get {
                return ResourceManager.GetString("TituloPrincipalReservaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista Usuarios.
        /// </summary>
        internal static string TituloprincipalUsuario {
            get {
                return ResourceManager.GetString("TituloprincipalUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variables.
        /// </summary>
        internal static string TituloprincipalVariables {
            get {
                return ResourceManager.GetString("TituloprincipalVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variables Suite.
        /// </summary>
        internal static string TituloPrincipalVariablesSuit {
            get {
                return ResourceManager.GetString("TituloPrincipalVariablesSuit", resourceCulture);
            }
        }
    }
}
